### ISSUE TITLE
Add navigation and dots CSS to support documentation

### ISSUE THREAD

**Issue by darrellschulte** [jnweaver/owl-slideshow-wp#8]
Invariably, users will want to change the color of the nav and dots elements on their slideshow. You may consider adding something like the following to the readme.txt, to a FAQ page (if you add the plugin to https://wordpress.org/plugins/) or the GitHub Wiki.

``` css
.owl-theme .owl-nav [class*=owl-]:hover {
  color: blue;
  background-color: transparent;
}

.owl-theme .owl-dots .owl-dot.active span, .owl-theme .owl-dots .owl-dot:hover span {
  background-color: blue;
}
```
